name: Docker Release

on:
  push:
    branches:
      - "main"
jobs:
  build-and-push:
    name: Build and Push Image docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible_version: [2.9.6, 2.10.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        id: docker_build
        env:
          DOCKER_BUILDKIT: '1'
          DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/ansible
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          build-args: ANSIBLE_VERSION=${{ matrix.ansible_version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ matrix.ansible_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
